import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {prepareDisplayReport,loadEditorialReport} from '../engine/editorial.mjs';
import {renderReport} from '../engine/renderer.mjs';
const source=await readFile('reports/student-a-2099-01.json','utf8');
const narrative=await readFile('sources/student-a-2099-01.reviewed.md','utf8');
const master=JSON.parse(source),display=JSON.parse(await readFile('reports/display/student-a-2099-01.json','utf8'));
const frozen=JSON.stringify({master,display});
const prepared=prepareDisplayReport(master,display,source,narrative);
assert.equal(JSON.stringify({master,display}),frozen,'Editorial layer does not mutate master/display');
const output=await renderReport(prepared);
assert.equal(output,await readFile('student-a-2099-01.html','utf8'));
assert.equal(output,await renderReport(await loadEditorialReport('reports/display/student-a-2099-01.json')));
assert(!output.includes(master.narrativeAnchor),'Full repeated narrative does not leak into parent report');
assert(!output.includes('sourceNarrativeSha256'),'Internal editorial metadata does not leak');
assert.deepEqual(prepared.classRecord,{scheduled:4,actual:5,additional:1});
assert.deepEqual(prepared.evidence,master.evidence);
assert.deepEqual(prepared.archiveReference,master.archiveReference);
assert(prepared.modules.some(m=>m.id==='monthly-overview'));
assert.equal(prepared.modules.find(m=>m.id==='grammar-experience').content.emphasis,'secondary');
assert(prepared.modules.find(m=>m.id==='reading-translation').content.callouts[0].text.includes('Synthetic phonics support'));
assert.equal((output.match(/<details /g)||[]).length,0);
assert.equal((output.match(/<summary>/g)||[]).length,0);
const clone=()=>structuredClone(display);
let invalid=clone();invalid.studentId='other';assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/identity mismatch/);
invalid=clone();invalid.editorial.sourceReportRevision=99;assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/source revision mismatch/);
invalid=clone();invalid.reportRevision=1;assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/advance/);
assert.throws(()=>prepareDisplayReport(master,display,source+' ',narrative),/hash mismatch/);
assert.throws(()=>prepareDisplayReport(master,display,source,narrative+'changed'),/hash mismatch/);
invalid=clone();invalid.classRecord={scheduled:16,actual:99,additional:83};assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/inherit authoritative/);
invalid=clone();invalid.modules[1].masterModuleRefs=['unknown'];assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/Unknown master module/);
invalid=clone();invalid.modules[1].evidenceRefs=['invented'];assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/Unknown evidence/);
invalid=clone();invalid.editorial.status='automatically-generated';assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/status/);
invalid=clone();invalid.modules[1].content.emphasis='onclick';assert.throws(()=>prepareDisplayReport(master,invalid,source,narrative),/emphasis/);
const inject=clone();inject.heroStory.title='<script>alert(1)</script>';assert((await renderReport(prepareDisplayReport(master,inject,source,narrative))).includes('&lt;script&gt;'));
// Array composition remains independent of a student or universal module order.
const changed=clone();[changed.modules[2],changed.modules[4]]=[changed.modules[4],changed.modules[2]];
const reordered=await renderReport(prepareDisplayReport(master,changed,source,narrative));assert(reordered.indexOf('speaking-transfer-learning-heading')<reordered.indexOf('reading-translation-learning-heading'));
const choi=await loadEditorialReport('reports/choi-yejun-2026-09.json');assert.equal(await renderReport(choi),await readFile('index.html','utf8'));
console.log('PASS: separate editorial contract, immutable source, provenance, source drift/identity/fact guards, concise composition, disclosure, escaping and Golden byte parity');
