import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {renderReport,validateReport,archiveUrl} from '../engine/renderer.mjs';
import {createFeedbackPayload,submitFeedback} from '../engine/feedback.mjs';
const data=JSON.parse(await readFile(new URL('../reports/choi-yejun-2026-09.json',import.meta.url),'utf8'));
assert.equal(await renderReport(data),await readFile(new URL('../index.html',import.meta.url),'utf8'),'generated artifact is current');
const subset=structuredClone(data);subset.modules=[data.modules[4],data.modules[3]];
let output=await renderReport(subset);
assert(output.indexOf('흩어진 단어에서')<output.indexOf('단어의 뜻을 넘어'));
assert(!output.includes('선생님의 관찰'));assert(!output.includes('Parent Feedback'));
const repeat=structuredClone(data);repeat.modules=[data.modules[4],{...data.modules[4],id:'another-building'}];
output=await renderReport(repeat);assert(output.includes('another-building-ev-building-heading'));
assert.throws(()=>validateReport({...data,reportId:undefined}),/Missing/);
assert.throws(()=>validateReport({...data,month:'2026-99'}),/month/);
assert.throws(()=>validateReport({...data,modules:[{id:'bad',type:'unknown',content:{}}]}),/Unknown/);
assert.throws(()=>validateReport({...data,modules:[data.modules[0],data.modules[0]]}),/duplicate/);
assert.equal(archiveUrl(data),data.student.defaultArchiveUrl);
assert.equal(archiveUrl({...data,archiveReference:{url:'https://drive.google.com/drive/folders/monthly'}}),'https://drive.google.com/drive/folders/monthly');
assert.throws(()=>archiveUrl({...data,archiveReference:{url:'javascript:alert(1)'}}),/Archive/);
const unavailable=structuredClone(data);delete unavailable.student.defaultArchiveUrl;
assert((await renderReport(unavailable)).includes('학습 기록물을 준비하고 있습니다.'));
const injected=structuredClone(data);injected.heroStory.hero_headline_1='<img src=x onerror=alert(1)>';
assert((await renderReport(injected)).includes('&lt;img src=x onerror=alert(1)&gt;'));
const payload=createFeedbackPayload(data,{readabilityScore:'5',growthClarityScore:'4',explanationClarityScore:'1',comment:'좋아요'},new Date('2026-10-02T10:00:00Z'));
assert.deepEqual(Object.keys(payload),['reportId','studentId','month','readabilityScore','growthClarityScore','explanationClarityScore','comment','createdAt']);
assert.equal(payload.createdAt,'2026-10-02T10:00:00.000Z');assert.equal(payload.readabilityScore,5);
assert.throws(()=>createFeedbackPayload(data,{readabilityScore:'0',growthClarityScore:'4',explanationClarityScore:'3'}));
assert.throws(()=>createFeedbackPayload(data,{readabilityScore:null,growthClarityScore:'4',explanationClarityScore:'3'}));
assert.equal((await submitFeedback(payload)).status,'unavailable');
assert.throws(()=>validateReport({...data,evidence:[{evidenceId:'x',kind:'ABILITY_SCORE'}]}),/evidence/);
console.log('PASS: static artifact, ordering, omission, repetition, data contract, Archive fallback, escaping, Feedback payload and unavailable adapter');

const variable=structuredClone(data);
variable.heroStory.paragraphs=variable.heroStory.paragraphs.slice(0,1);
variable.modules.find(m=>m.type==='reading-vocabulary').vocabulary=['one','two'];
variable.modules.find(m=>m.type==='learning-continuum').steps=variable.modules.find(m=>m.type==='learning-continuum').steps.slice(0,3);
variable.modules.find(m=>m.type==='sentence-building').patterns=variable.modules.find(m=>m.type==='sentence-building').patterns.slice(0,1);
variable.modules.find(m=>m.type==='sentence-building').patterns[0].examples=['one example'];
output=await renderReport(variable);
assert.equal((output.match(/class="vocab-pill"/g)||[]).length,2);
assert.equal((output.match(/class="sample-sentence"/g)||[]).length,1);
assert.equal((output.match(/class="stepper-step /g)||[]).length,3);
const minimal=structuredClone(data);minimal.modules=[data.modules[3]];minimal.classRecord=null;await renderReport(minimal);
console.log('PASS: variable paragraph, vocabulary, continuum, pattern/example counts; no required attendance when its module is omitted');
