import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {renderReport,validateReport,archiveUrl} from '../engine/renderer.mjs';
import {createFeedbackPayload,submitFeedback} from '../engine/feedback.mjs';
const json=async path=>JSON.parse(await readFile(path,'utf8'));
const soyun=await json('reports/kim-soyun-2026-09.json');
const choi=await json('reports/choi-yejun-2026-09.json');
const html=await renderReport(soyun);
assert.equal(html,await readFile('kim-soyun-2026-09.html','utf8'));
assert.equal(await renderReport(choi),await readFile('index.html','utf8'),'Choi byte parity');
assert.equal(archiveUrl(soyun),'https://drive.google.com/drive/folders/1hmpyOJObiaH80_HqF4ZLAElhJ3AMUMg9');
const expected=['hero','monthly-overview','reading-translation','sentence-building','speaking-transfer','grammar-experience','teacher-interpretation','next-step','class-record','learning-archive','parent-feedback','brand-ending'];
assert.deepEqual(soyun.modules.map(m=>m.id),expected);
assert.equal(soyun.modules.filter(m=>m.type==='learning-narrative').length,5);
assert.equal(soyun.modules.some(m=>m.type==='learning-continuum'),false);
assert.equal(soyun.evidence.length,12);
assert.deepEqual(soyun.classRecord,{scheduled:16,actual:17,additional:1});
assert.equal(html.includes(soyun.narrativeAnchor),true);
assert.equal(html.includes('최예준'),false);
const decoded=html.replaceAll('&#39;',"'").replaceAll('&amp;','&');
for(const text of ['What We Make with Milk','3D Shapes','Amazing Animal Senses','My Neighborhood','How We Use Air','What Time Is It There?','Hello, Fish!',"Van Gogh's Paintings",'Flags, Flags','Day and Night',"It's sunny.",'My favorite sport is tennis.','I ride my bike.','I do my homework.','I practice the piano.',"It's on the chair.","It's under the desk.","It's in the toy box.",'have/has + P.P.','eat – ate – eaten','see – saw – seen','go – went – gone','take – took – taken','write – wrote – written','banana + that is yellow','a TV that has a big screen','Is it under the chair?','말하기가 자동화되었다고 판단할 근거는 충분하지 않습니다']) assert(decoded.includes(text),text);
assert(!/Reading 90|Speaking 85|Grammar 95|Lexile|radar|ranking/.test(decoded));
const fragment=x=>x.match(/<form data-feedback>[\s\S]*?<\/form>/)[0].replace(/(<input type="hidden" name="(?:reportId|studentId|month)" value=")[^"]*/g,'$1IDENTITY');
assert.equal(fragment(html),fragment(await renderReport(choi)),'shared feedback exact markup');
const payload=createFeedbackPayload(soyun,{readabilityScore:5,growthClarityScore:4,explanationClarityScore:3,comment:'의견'},new Date('2026-10-02T00:00:00Z'));
assert.deepEqual(payload,{reportId:'kim-soyun-2026-09',studentId:'kim-soyun',month:'2026-09',readabilityScore:5,growthClarityScore:4,explanationClarityScore:3,comment:'의견',createdAt:'2026-10-02T00:00:00.000Z'});
assert.equal((await submitFeedback(payload)).status,'unavailable');
const reordered=structuredClone(soyun);[reordered.modules[2],reordered.modules[4]]=[reordered.modules[4],reordered.modules[2]];
const composed=await renderReport(reordered);assert(composed.indexOf('id="speaking-transfer-narrative-heading"')<composed.indexOf('id="reading-translation-narrative-heading"'));
const omitted=structuredClone(soyun);omitted.modules=omitted.modules.filter(m=>m.id!=='grammar-experience');assert(!(await renderReport(omitted)).includes('id="grammar-experience-narrative-heading"'));
const bad=structuredClone(soyun);bad.modules[2].evidenceRefs=['missing'];assert.throws(()=>validateReport(bad),/Unknown evidence/);
const injected=structuredClone(soyun);injected.modules[1].content.title='<script>alert(1)</script>';assert((await renderReport(injected)).includes('&lt;script&gt;alert(1)&lt;/script&gt;'));
console.log('PASS: second student content, order, omission/reorder, evidence refs, escaping, archive, shared feedback/payload, Choi byte parity');
